theme: jekyll-theme-slate
title: Ricky Safran
description: <b>21, Bay Area, CA</b> <br>I have 2 years of coding experience. I am proficient with R, Python, and SQL. Coding is the future and I am looking forward to continually improving my abilities!</br>
